// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

public final class Broker {
  private Broker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Module_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Module_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetModulesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetModulesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014broker.proto\"\016\n\014EmptyMessage\" \n\020Handsh" +
      "akeRequest\022\014\n\004type\030\001 \002(\t\"\037\n\021HandshakeRes" +
      "ponse\022\n\n\002ok\030\001 \002(\010\"\"\n\006Module\022\014\n\004type\030\001 \002(" +
      "\t\022\n\n\002id\030\002 \002(\003\".\n\022GetModulesResponse\022\030\n\007m" +
      "odules\030\001 \003(\0132\007.Module\"\037\n\020SubscribeReques" +
      "t\022\013\n\003ids\030\001 \003(\003\"1\n\021SubscribeResponse\022\n\n\002o" +
      "k\030\001 \002(\010\022\020\n\010wrongIds\030\002 \003(\003\"5\n\016MessageRequ" +
      "est\022\022\n\nidReceiver\030\001 \001(\003\022\017\n\007message\030\002 \002(\t" +
      "2\377\001\n\rBrokerService\0222\n\thandshake\022\021.Handsh" +
      "akeRequest\032\022.HandshakeResponse\0220\n\ngetMod" +
      "ules\022\r.EmptyMessage\032\023.GetModulesResponse" +
      "\0222\n\tsubscribe\022\021.SubscribeRequest\032\022.Subsc" +
      "ribeResponse\022-\n\013sendMessage\022\017.MessageReq" +
      "uest\032\r.EmptyMessage\022%\n\005close\022\r.EmptyMess" +
      "age\032\r.EmptyMessageB\030\n\014proto.brokerB\006Brok" +
      "erP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyMessage_descriptor,
        new java.lang.String[] { });
    internal_static_HandshakeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HandshakeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_HandshakeResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HandshakeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeResponse_descriptor,
        new java.lang.String[] { "Ok", });
    internal_static_Module_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Module_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Module_descriptor,
        new java.lang.String[] { "Type", "Id", });
    internal_static_GetModulesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetModulesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetModulesResponse_descriptor,
        new java.lang.String[] { "Modules", });
    internal_static_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeRequest_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_SubscribeResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SubscribeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeResponse_descriptor,
        new java.lang.String[] { "Ok", "WrongIds", });
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "IdReceiver", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
