// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

public final class Broker {
  private Broker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Module_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Module_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetModulesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetModulesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014broker.proto\"\016\n\014EmptyMessage\":\n\020Handsh" +
      "akeRequest\022\014\n\004type\030\001 \002(\t\022\n\n\002ip\030\002 \002(\t\022\014\n\004" +
      "port\030\003 \002(\003\"\037\n\021HandshakeResponse\022\n\n\002ok\030\001 " +
      "\002(\010\"\"\n\006Module\022\014\n\004type\030\001 \002(\t\022\n\n\002id\030\002 \002(\003\"" +
      ".\n\022GetModulesResponse\022\030\n\007modules\030\001 \003(\0132\007" +
      ".Module\"\037\n\020SubscribeRequest\022\013\n\003ids\030\001 \003(\003" +
      "\"1\n\021SubscribeResponse\022\n\n\002ok\030\001 \002(\010\022\020\n\010wro" +
      "ngIds\030\002 \003(\003\"5\n\016MessageRequest\022\022\n\nidRecei" +
      "ver\030\001 \001(\003\022\017\n\007message\030\002 \002(\t2\377\001\n\rBrokerSer" +
      "vice\0222\n\thandshake\022\021.HandshakeRequest\032\022.H" +
      "andshakeResponse\0220\n\ngetModules\022\r.EmptyMe" +
      "ssage\032\023.GetModulesResponse\0222\n\tsubscribe\022" +
      "\021.SubscribeRequest\032\022.SubscribeResponse\022-" +
      "\n\013sendMessage\022\017.MessageRequest\032\r.EmptyMe" +
      "ssage\022%\n\005close\022\r.EmptyMessage\032\r.EmptyMes" +
      "sageB\030\n\014proto.brokerB\006BrokerP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyMessage_descriptor,
        new java.lang.String[] { });
    internal_static_HandshakeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HandshakeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeRequest_descriptor,
        new java.lang.String[] { "Type", "Ip", "Port", });
    internal_static_HandshakeResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HandshakeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeResponse_descriptor,
        new java.lang.String[] { "Ok", });
    internal_static_Module_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Module_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Module_descriptor,
        new java.lang.String[] { "Type", "Id", });
    internal_static_GetModulesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetModulesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetModulesResponse_descriptor,
        new java.lang.String[] { "Modules", });
    internal_static_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeRequest_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_SubscribeResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SubscribeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeResponse_descriptor,
        new java.lang.String[] { "Ok", "WrongIds", });
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "IdReceiver", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
