// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
