// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

public interface EmptyIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.EmptyIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 idRequester = 1;</code>
   * @return Whether the idRequester field is set.
   */
  boolean hasIdRequester();
  /**
   * <code>required int64 idRequester = 1;</code>
   * @return The idRequester.
   */
  long getIdRequester();
}
