// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

public interface HandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.HandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string type = 1;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>required string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>required string ip = 2;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <code>required string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>required string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>required int64 port = 3;</code>
   * @return Whether the port field is set.
   */
  boolean hasPort();
  /**
   * <code>required int64 port = 3;</code>
   * @return The port.
   */
  long getPort();
}
