// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

public interface HandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string type = 1;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>required string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
