// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 idReceiver = 1;</code>
   * @return Whether the idReceiver field is set.
   */
  boolean hasIdReceiver();
  /**
   * <code>optional int64 idReceiver = 1;</code>
   * @return The idReceiver.
   */
  long getIdReceiver();

  /**
   * <code>required string message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>required string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>required string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
