// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package proto.broker;

/**
 * Protobuf type {@code broker.SubscribeResponse}
 */
public  final class SubscribeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:broker.SubscribeResponse)
    SubscribeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeResponse.newBuilder() to construct.
  private SubscribeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeResponse() {
    wrongId_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscribeResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubscribeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            ok_ = input.readBool();
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              wrongId_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            wrongId_.addLong(input.readInt64());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              wrongId_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              wrongId_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        wrongId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.broker.BrokerProto.internal_static_broker_SubscribeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.broker.BrokerProto.internal_static_broker_SubscribeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.broker.SubscribeResponse.class, proto.broker.SubscribeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_;
  /**
   * <code>required bool ok = 1;</code>
   * @return Whether the ok field is set.
   */
  public boolean hasOk() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required bool ok = 1;</code>
   * @return The ok.
   */
  public boolean getOk() {
    return ok_;
  }

  public static final int WRONGID_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList wrongId_;
  /**
   * <code>repeated int64 wrongId = 2;</code>
   * @return A list containing the wrongId.
   */
  public java.util.List<java.lang.Long>
      getWrongIdList() {
    return wrongId_;
  }
  /**
   * <code>repeated int64 wrongId = 2;</code>
   * @return The count of wrongId.
   */
  public int getWrongIdCount() {
    return wrongId_.size();
  }
  /**
   * <code>repeated int64 wrongId = 2;</code>
   * @param index The index of the element to return.
   * @return The wrongId at the given index.
   */
  public long getWrongId(int index) {
    return wrongId_.getLong(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasOk()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, ok_);
    }
    for (int i = 0; i < wrongId_.size(); i++) {
      output.writeInt64(2, wrongId_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ok_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < wrongId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(wrongId_.getLong(i));
      }
      size += dataSize;
      size += 1 * getWrongIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.broker.SubscribeResponse)) {
      return super.equals(obj);
    }
    proto.broker.SubscribeResponse other = (proto.broker.SubscribeResponse) obj;

    if (hasOk() != other.hasOk()) return false;
    if (hasOk()) {
      if (getOk()
          != other.getOk()) return false;
    }
    if (!getWrongIdList()
        .equals(other.getWrongIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOk()) {
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
    }
    if (getWrongIdCount() > 0) {
      hash = (37 * hash) + WRONGID_FIELD_NUMBER;
      hash = (53 * hash) + getWrongIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.broker.SubscribeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.broker.SubscribeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.broker.SubscribeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.broker.SubscribeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.broker.SubscribeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.broker.SubscribeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.broker.SubscribeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.broker.SubscribeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.broker.SubscribeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.broker.SubscribeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.broker.SubscribeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.broker.SubscribeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.broker.SubscribeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code broker.SubscribeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:broker.SubscribeResponse)
      proto.broker.SubscribeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.broker.BrokerProto.internal_static_broker_SubscribeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.broker.BrokerProto.internal_static_broker_SubscribeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.broker.SubscribeResponse.class, proto.broker.SubscribeResponse.Builder.class);
    }

    // Construct using proto.broker.SubscribeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ok_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      wrongId_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.broker.BrokerProto.internal_static_broker_SubscribeResponse_descriptor;
    }

    @java.lang.Override
    public proto.broker.SubscribeResponse getDefaultInstanceForType() {
      return proto.broker.SubscribeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public proto.broker.SubscribeResponse build() {
      proto.broker.SubscribeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.broker.SubscribeResponse buildPartial() {
      proto.broker.SubscribeResponse result = new proto.broker.SubscribeResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ok_ = ok_;
        to_bitField0_ |= 0x00000001;
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        wrongId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.wrongId_ = wrongId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.broker.SubscribeResponse) {
        return mergeFrom((proto.broker.SubscribeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.broker.SubscribeResponse other) {
      if (other == proto.broker.SubscribeResponse.getDefaultInstance()) return this;
      if (other.hasOk()) {
        setOk(other.getOk());
      }
      if (!other.wrongId_.isEmpty()) {
        if (wrongId_.isEmpty()) {
          wrongId_ = other.wrongId_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureWrongIdIsMutable();
          wrongId_.addAll(other.wrongId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasOk()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.broker.SubscribeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.broker.SubscribeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean ok_ ;
    /**
     * <code>required bool ok = 1;</code>
     * @return Whether the ok field is set.
     */
    public boolean hasOk() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bool ok = 1;</code>
     * @return The ok.
     */
    public boolean getOk() {
      return ok_;
    }
    /**
     * <code>required bool ok = 1;</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {
      bitField0_ |= 0x00000001;
      ok_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool ok = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ok_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList wrongId_ = emptyLongList();
    private void ensureWrongIdIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        wrongId_ = mutableCopy(wrongId_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int64 wrongId = 2;</code>
     * @return A list containing the wrongId.
     */
    public java.util.List<java.lang.Long>
        getWrongIdList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(wrongId_) : wrongId_;
    }
    /**
     * <code>repeated int64 wrongId = 2;</code>
     * @return The count of wrongId.
     */
    public int getWrongIdCount() {
      return wrongId_.size();
    }
    /**
     * <code>repeated int64 wrongId = 2;</code>
     * @param index The index of the element to return.
     * @return The wrongId at the given index.
     */
    public long getWrongId(int index) {
      return wrongId_.getLong(index);
    }
    /**
     * <code>repeated int64 wrongId = 2;</code>
     * @param index The index to set the value at.
     * @param value The wrongId to set.
     * @return This builder for chaining.
     */
    public Builder setWrongId(
        int index, long value) {
      ensureWrongIdIsMutable();
      wrongId_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 wrongId = 2;</code>
     * @param value The wrongId to add.
     * @return This builder for chaining.
     */
    public Builder addWrongId(long value) {
      ensureWrongIdIsMutable();
      wrongId_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 wrongId = 2;</code>
     * @param values The wrongId to add.
     * @return This builder for chaining.
     */
    public Builder addAllWrongId(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureWrongIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, wrongId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 wrongId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWrongId() {
      wrongId_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:broker.SubscribeResponse)
  }

  // @@protoc_insertion_point(class_scope:broker.SubscribeResponse)
  private static final proto.broker.SubscribeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.broker.SubscribeResponse();
  }

  public static proto.broker.SubscribeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SubscribeResponse>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeResponse>() {
    @java.lang.Override
    public SubscribeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubscribeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubscribeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscribeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.broker.SubscribeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

