// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package proto.module;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:module.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
