// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package proto.module;

public interface ModuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Module)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string type = 1;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>required string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>required int64 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
