// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package proto.module;

/**
 * Protobuf type {@code module.WelcomeRequest}
 */
public  final class WelcomeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:module.WelcomeRequest)
    WelcomeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WelcomeRequest.newBuilder() to construct.
  private WelcomeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WelcomeRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WelcomeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WelcomeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            proto.module.Module.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = module_.toBuilder();
            }
            module_ = input.readMessage(proto.module.Module.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(module_);
              module_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.module.ModuleProto.internal_static_module_WelcomeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.module.ModuleProto.internal_static_module_WelcomeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.module.WelcomeRequest.class, proto.module.WelcomeRequest.Builder.class);
  }

  private int bitField0_;
  public static final int MODULE_FIELD_NUMBER = 1;
  private proto.module.Module module_;
  /**
   * <code>required .module.Module module = 1;</code>
   * @return Whether the module field is set.
   */
  public boolean hasModule() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .module.Module module = 1;</code>
   * @return The module.
   */
  public proto.module.Module getModule() {
    return module_ == null ? proto.module.Module.getDefaultInstance() : module_;
  }
  /**
   * <code>required .module.Module module = 1;</code>
   */
  public proto.module.ModuleOrBuilder getModuleOrBuilder() {
    return module_ == null ? proto.module.Module.getDefaultInstance() : module_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasModule()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getModule().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getModule());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getModule());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.module.WelcomeRequest)) {
      return super.equals(obj);
    }
    proto.module.WelcomeRequest other = (proto.module.WelcomeRequest) obj;

    if (hasModule() != other.hasModule()) return false;
    if (hasModule()) {
      if (!getModule()
          .equals(other.getModule())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasModule()) {
      hash = (37 * hash) + MODULE_FIELD_NUMBER;
      hash = (53 * hash) + getModule().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.module.WelcomeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.module.WelcomeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.module.WelcomeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.module.WelcomeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.module.WelcomeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.module.WelcomeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.module.WelcomeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.module.WelcomeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.module.WelcomeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.module.WelcomeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.module.WelcomeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.module.WelcomeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.module.WelcomeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code module.WelcomeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:module.WelcomeRequest)
      proto.module.WelcomeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.module.ModuleProto.internal_static_module_WelcomeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.module.ModuleProto.internal_static_module_WelcomeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.module.WelcomeRequest.class, proto.module.WelcomeRequest.Builder.class);
    }

    // Construct using proto.module.WelcomeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getModuleFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (moduleBuilder_ == null) {
        module_ = null;
      } else {
        moduleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.module.ModuleProto.internal_static_module_WelcomeRequest_descriptor;
    }

    @java.lang.Override
    public proto.module.WelcomeRequest getDefaultInstanceForType() {
      return proto.module.WelcomeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public proto.module.WelcomeRequest build() {
      proto.module.WelcomeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.module.WelcomeRequest buildPartial() {
      proto.module.WelcomeRequest result = new proto.module.WelcomeRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (moduleBuilder_ == null) {
          result.module_ = module_;
        } else {
          result.module_ = moduleBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.module.WelcomeRequest) {
        return mergeFrom((proto.module.WelcomeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.module.WelcomeRequest other) {
      if (other == proto.module.WelcomeRequest.getDefaultInstance()) return this;
      if (other.hasModule()) {
        mergeModule(other.getModule());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasModule()) {
        return false;
      }
      if (!getModule().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.module.WelcomeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.module.WelcomeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private proto.module.Module module_;
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.module.Module, proto.module.Module.Builder, proto.module.ModuleOrBuilder> moduleBuilder_;
    /**
     * <code>required .module.Module module = 1;</code>
     * @return Whether the module field is set.
     */
    public boolean hasModule() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .module.Module module = 1;</code>
     * @return The module.
     */
    public proto.module.Module getModule() {
      if (moduleBuilder_ == null) {
        return module_ == null ? proto.module.Module.getDefaultInstance() : module_;
      } else {
        return moduleBuilder_.getMessage();
      }
    }
    /**
     * <code>required .module.Module module = 1;</code>
     */
    public Builder setModule(proto.module.Module value) {
      if (moduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        module_ = value;
        onChanged();
      } else {
        moduleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .module.Module module = 1;</code>
     */
    public Builder setModule(
        proto.module.Module.Builder builderForValue) {
      if (moduleBuilder_ == null) {
        module_ = builderForValue.build();
        onChanged();
      } else {
        moduleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .module.Module module = 1;</code>
     */
    public Builder mergeModule(proto.module.Module value) {
      if (moduleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            module_ != null &&
            module_ != proto.module.Module.getDefaultInstance()) {
          module_ =
            proto.module.Module.newBuilder(module_).mergeFrom(value).buildPartial();
        } else {
          module_ = value;
        }
        onChanged();
      } else {
        moduleBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .module.Module module = 1;</code>
     */
    public Builder clearModule() {
      if (moduleBuilder_ == null) {
        module_ = null;
        onChanged();
      } else {
        moduleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .module.Module module = 1;</code>
     */
    public proto.module.Module.Builder getModuleBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getModuleFieldBuilder().getBuilder();
    }
    /**
     * <code>required .module.Module module = 1;</code>
     */
    public proto.module.ModuleOrBuilder getModuleOrBuilder() {
      if (moduleBuilder_ != null) {
        return moduleBuilder_.getMessageOrBuilder();
      } else {
        return module_ == null ?
            proto.module.Module.getDefaultInstance() : module_;
      }
    }
    /**
     * <code>required .module.Module module = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.module.Module, proto.module.Module.Builder, proto.module.ModuleOrBuilder> 
        getModuleFieldBuilder() {
      if (moduleBuilder_ == null) {
        moduleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.module.Module, proto.module.Module.Builder, proto.module.ModuleOrBuilder>(
                getModule(),
                getParentForChildren(),
                isClean());
        module_ = null;
      }
      return moduleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:module.WelcomeRequest)
  }

  // @@protoc_insertion_point(class_scope:module.WelcomeRequest)
  private static final proto.module.WelcomeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.module.WelcomeRequest();
  }

  public static proto.module.WelcomeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WelcomeRequest>
      PARSER = new com.google.protobuf.AbstractParser<WelcomeRequest>() {
    @java.lang.Override
    public WelcomeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WelcomeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WelcomeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WelcomeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.module.WelcomeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

