# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='module.proto',
  package='module',
  syntax='proto2',
  serialized_options=b'\n\014proto.moduleB\013ModuleProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmodule.proto\x12\x06module\"\x0e\n\x0c\x45mptyMessage\"3\n\x0eMessageRequest\x12\x10\n\x08idSender\x18\x01 \x02(\x03\x12\x0f\n\x07message\x18\x02 \x02(\t\"\"\n\x06Module\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x03\"0\n\x0eWelcomeRequest\x12\x1e\n\x06module\x18\x01 \x02(\x0b\x32\x0e.module.Module\"0\n\x0eGoodByeRequest\x12\x1e\n\x06module\x18\x01 \x02(\x0b\x32\x0e.module.Module2\xf6\x01\n\rModuleService\x12>\n\x0ereceiveMessage\x12\x16.module.MessageRequest\x1a\x14.module.EmptyMessage\x12\x33\n\x05\x63lose\x12\x14.module.EmptyMessage\x1a\x14.module.EmptyMessage\x12\x37\n\x07welcome\x12\x16.module.WelcomeRequest\x1a\x14.module.EmptyMessage\x12\x37\n\x07goodBye\x12\x16.module.GoodByeRequest\x1a\x14.module.EmptyMessageB\x1d\n\x0cproto.moduleB\x0bModuleProtoP\x01'
)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='module.EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=38,
)


_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='module.MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idSender', full_name='module.MessageRequest.idSender', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='module.MessageRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=91,
)


_MODULE = _descriptor.Descriptor(
  name='Module',
  full_name='module.Module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='module.Module.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='module.Module.id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=127,
)


_WELCOMEREQUEST = _descriptor.Descriptor(
  name='WelcomeRequest',
  full_name='module.WelcomeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='module.WelcomeRequest.module', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=177,
)


_GOODBYEREQUEST = _descriptor.Descriptor(
  name='GoodByeRequest',
  full_name='module.GoodByeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='module.GoodByeRequest.module', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=227,
)

_WELCOMEREQUEST.fields_by_name['module'].message_type = _MODULE
_GOODBYEREQUEST.fields_by_name['module'].message_type = _MODULE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['Module'] = _MODULE
DESCRIPTOR.message_types_by_name['WelcomeRequest'] = _WELCOMEREQUEST
DESCRIPTOR.message_types_by_name['GoodByeRequest'] = _GOODBYEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'module_pb2'
  # @@protoc_insertion_point(class_scope:module.EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUEST,
  '__module__' : 'module_pb2'
  # @@protoc_insertion_point(class_scope:module.MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

Module = _reflection.GeneratedProtocolMessageType('Module', (_message.Message,), {
  'DESCRIPTOR' : _MODULE,
  '__module__' : 'module_pb2'
  # @@protoc_insertion_point(class_scope:module.Module)
  })
_sym_db.RegisterMessage(Module)

WelcomeRequest = _reflection.GeneratedProtocolMessageType('WelcomeRequest', (_message.Message,), {
  'DESCRIPTOR' : _WELCOMEREQUEST,
  '__module__' : 'module_pb2'
  # @@protoc_insertion_point(class_scope:module.WelcomeRequest)
  })
_sym_db.RegisterMessage(WelcomeRequest)

GoodByeRequest = _reflection.GeneratedProtocolMessageType('GoodByeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GOODBYEREQUEST,
  '__module__' : 'module_pb2'
  # @@protoc_insertion_point(class_scope:module.GoodByeRequest)
  })
_sym_db.RegisterMessage(GoodByeRequest)


DESCRIPTOR._options = None

_MODULESERVICE = _descriptor.ServiceDescriptor(
  name='ModuleService',
  full_name='module.ModuleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=230,
  serialized_end=476,
  methods=[
  _descriptor.MethodDescriptor(
    name='receiveMessage',
    full_name='module.ModuleService.receiveMessage',
    index=0,
    containing_service=None,
    input_type=_MESSAGEREQUEST,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='close',
    full_name='module.ModuleService.close',
    index=1,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='welcome',
    full_name='module.ModuleService.welcome',
    index=2,
    containing_service=None,
    input_type=_WELCOMEREQUEST,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='goodBye',
    full_name='module.ModuleService.goodBye',
    index=3,
    containing_service=None,
    input_type=_GOODBYEREQUEST,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODULESERVICE)

DESCRIPTOR.services_by_name['ModuleService'] = _MODULESERVICE

# @@protoc_insertion_point(module_scope)
