// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pp.proto

package broker.proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 age = 1;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>required int64 age = 1;</code>
   * @return The age.
   */
  long getAge();
}
